<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.16">
  <POU Name="MAIN" Id="{7d680b2f-8db9-4f1e-8602-1c7527d7b88c}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
    bStartupDone   : BOOL := FALSE;   // runs once on boot
    tonStartDelay  : TON;             // small delay to let DALI bus settle first
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[
POU();
WallLight_POU();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="190" Count="1" />
      <LineId Id="158" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>