<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.16">
  <POU Name="POU_WALLLIGHT" Id="{840098ec-0897-43ea-8320-196cc3c37fca}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM POU_WALLLIGHT
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="POU_WALLLIGHT">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>