<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.16">
  <POU Name="PyADS_POU" Id="{54d07951-3b08-4405-80a5-226f71580db2}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PyADS_POU
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="PyADS_POU">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>